version: "3.8"

services:
  app:
    container_name: fswatch-command
    image: brevyhq/fswatch-command
    build:
      context: .
    volumes:
      - ./configs:/configs
      - ./watch:/watch
      - ./scripts:/scripts
    env_file:
      - .env